### PR TITLE
Fix makefile

### PR DESCRIPTION
**Pull request by daniel071**
Resolves build issues in #7
You should upload a new build as the current one is broken.
If anyone would like a currently working build, they can find it [here](https://pavela.net/ProxyChecker.jar)

### CODE REVIEW

**Comment by plumped** [comment]
Nice thank you!

Can you please recap step by step how you got it to work?
I dont think the initiator is still working on this....

**Comment by daniel071** [comment]
If you would like to compile it own, you can run this in your terminal or command prompt:
```shell
git clone https://github.com/daniel071/ProxyChecker.git
cd ProxyChecker
make
java -jar artifact/ProxyChecker.jar
```
The error in the makefile showed that the repo it was trying to download from was invalid, so I searched for a current link and changed it to a working one.
And yes, the current maintainer seems to be inactive so I may make my own maintained fork with more changes.

**Comment by plumped** [comment]
Thanks a lot! My problem is javaFX.... 
1. I hate it
2. how do you get it running above jdk11 ?

**Comment by daniel071** [comment]
I would just compile with java 8 or java 11 for now. For any newer versions, I would do the same as what has already been done with gson. But porting ProxyChecker to newer java versions may have some issues too. If you use Intellij you could add as a maven dependency in the pom.xml.
https://mvnrepository.com/artifact/org.openjfx/javafx/16

**Comment by faiqsohail** [comment]
LGTM, thanks for making those changes 👍

**Pull request merged**
